#! /bin/sh
#
### BEGIN INIT INFO
# Provides:             deckard-node 
# Required-Start:       $network $local_fs $remote_fs dbus
# Required-Stop:        $network $local_fs $remote_fs dbus
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Deckard-node
# Description:          init script for the Deckard-node.
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:
NAME=deckard-node
DESC="deckard-node"
PIDDIR=/var/run/$NAME
PIDFILE=$PIDDIR/$NAME.pid
DAEMON=/usr/local/bin/deckard-node
USER=sne
GROUP=sne

test -x $DAEMON || exit 0

DAEMON_OPTS="-s 95.211.149.20"


## Include defaults if available
#if [ -f /etc/default/$NAME ] ; then
#        . /etc/default/$NAME
#fi

. /lib/init/vars.sh
. /lib/lsb/init-functions

case "$1" in
  start)
        [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
        [ -d $PIDDIR ] || install -o $USER -d $PIDDIR
        start-stop-daemon --start \
              --make-pidfile \
              --pidfile $PIDFILE \
              --chuid $USER:$GROUP \
              --background \
              --exec $DAEMON \
              -- $DAEMON_OPTS
        echo `cat $PIDFILE`
        case "$?" in
                0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
                2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
        esac
        ;;
  stop)
        [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
        start-stop-daemon --stop --quiet \
                --retry=TERM/30/KILL/5 \
                --name $NAME
        case "$?" in
                0|1)    rm -f $PIDFILE
                        [ "$VERBOSE" != no ] && log_end_msg 0
                        ;;
                2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
        esac
        ;;
  status)
        if start-stop-daemon --test --stop --quiet \
                --pidfile $PIDFILE \
                --user $USER \
                --exec $DAEMON
        then
                [ "$VERBOSE" != no ] && echo "$DESC is running."
                exit 0
        else
                [ "$VERBOSE" != no ] && echo "$DESC is not running"
                exit 3
        fi
        ;;
  force-reload)
        start-stop-daemon --stop --test --quiet \
                --name $NAME \
        && $0 restart || exit 0
        ;;
  restart)
        [ "$VERBOSE" != no ] && log_daemon_msg "Restarting $DESC" "$NAME"
        start-stop-daemon --stop --quiet \
                --retry=TERM/30/KILL/5 \
                --name $NAME
        case "$?" in
                0|1)
                        [ -d $PIDDIR ] || install -o $USER -d $PIDDIR
                        rm -f $PIDFILE
                        start-stop-daemon --start --quiet \
                              --make-pidfile \
                              --pidfile $PIDFILE \
                              --chuid $USER:$GROUP \
                              --background \
                              --exec $DAEMON \
                              -- $DAEMON_OPTS
                        case "$?" in
                                0) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
                                *) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
                        esac
                        ;;
                *)
                        [ "$VERBOSE" != no ] && log_end_msg 0
                        ;;
        esac
        ;;
  *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|force-reload}" >&2
        exit 3
        ;;
esac

exit 0
