#!/usr/bin/env bash

userlist=/opt/graphite/users.list

rm $userlist
cd /home
for username in $(members ring-users); do
    passfile=/home/${username}/graphite.pass
    if [ -d $passfile ]; then
        >&2 echo "$passfile is a directory"
    fi
    if [ -f $passfile ]; then
        if [ $(head -1 $passfile) ]; then
            echo -n "$username:" >> $userlist
            head -1 $passfile >> $userlist
        fi
    fi
done
