#!/usr/bin/env bash

cd /home
for username in $(members ring-users); do
    keyfile=/home/${username}/ssh-keys
    if [ -d $keyfile ]; then
        >&2 echo "$keyfile is a directory"
    fi
    if [ -f $keyfile ]; then
        /usr/bin/install -m 0444 /home/${username}/ssh-keys /opt/keys/${username}.sshkeys
    fi
done
/usr/bin/install -m 0444 /home/claranet/ssh-keys-only-claranet /opt/keys/claranet-only.sshkeys
