#!/usr/bin/env bash
# this file is fed into the virtual machines that are created and thus
# we can let them become part of the ring automaticly

/usr/sbin/puppetd --test --debug
sleep 60;
/usr/sbin/puppetd --test --debug
echo "# Puppet Name: puppetagent" >> /var/spool/cron/crontabs/root
echo "15,45 * * * * /usr/sbin/puppetd --test" >> /var/spool/cron/crontabs/root
$(EDITOR=touch crontab -e)
chmod 0600 /var/spool/cron/crontabs/root
