#!/bin/sh

NODEFQDN=$(hostname)
NODE=$(hostname -s)
ORG=$(echo $NODE |sed 's/..$//')
LOCALADMIN=$(getent passwd $ORG | cut -d : -f 5)

# ASN Info
IPV4ADDR=$(ip -4 route get 255.255.255.255 2>/dev/null | grep src | sed 's/.*src //' | sed 's/ $//')
#IPV4ADDR=$(dig +short A $NODEFQDN | grep -v '\.$')
IPV6ADDR=$(ip -6 route get 2001:6e0:100:4001::3 2>/dev/null | grep src | sed 's/.*src //' | sed 's/ *metric.*$//')

if [ -n "$IPV4ADDR" ];
then
	ASN=$(dig +short TXT $(echo $IPV4ADDR | awk -F . '{print $4"."$3"."$2"."$1".asn.routeviews.org"}') | awk '{print $1}' | sed 's/"//g')
	CYMRUASINFO=$(dig +short TXT AS$ASN.asn.cymru.com | sed 's/"//g')
	REGION=$(echo $CYMRUASINFO | cut -d \| -f 3 | sed 's/^ //' | sed 's/ $//')
	ASINFO=$(echo $CYMRUASINFO | cut -d \| -f 5 | sed 's/^ //' | sed 's/ $//')
fi
LOCATION=$(whois $(echo $IPV6ADDR) 2>/dev/null|grep -i ^country)
if [ -n "$LOCATION" ]; then
        LOCATION=$(grep $(echo "$LOCATION "|head -n1|awk '{print "^"$2}') /usr/share/zoneinfo/iso3166.tab|cut -f2)
fi

# NLNOG RING Logo - can be disabled :)
cat /etc/update-motd.d/ring.nlnog.net-logo

echo
echo "  Welcome on $NODEFQDN, an NLNOG RING Node!"
echo "  System operated by $LOCALADMIN"
if [ -n "$ASN" ];
then
	echo "  Location: $LOCATION, $REGION - AS$ASN ($ASINFO)"
else	
	echo "  Location: $LOCATION"
fi

# Munin / Nagios / Smokeping

echo 
echo "  Smokeping / Nagios / Munin:"
echo
echo "  https://ring.nlnog.net/cgi-bin/nagios3/status.cgi?host=$NODEFQDN"
echo "  https://ring.nlnog.net/munin/ring.nlnog.net/$NODEFQDN"

echo
echo "  For more information, please visit https://ring.nlnog.net/"
